POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QyIiwiaWQiOiI2NDFiYThlMGNmMTQzMGMwODkxOTk3OTYiLCJpYXQiOjE2Nzk1MzQzMTJ9.-7yT3flXTnf75MDs3K-cmKeC-fao0XbPprt1cem8XO4

{
  "title": "This is a new post six",
  "author": "AL",
  "url": "http://a.b.com",
  "likes": 2020
}

###
DELETE http://localhost:3003/api/blogs/641bbb8c381c30b4afea4daf
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QyIiwiaWQiOiI2NDFiYThlMGNmMTQzMGMwODkxOTk3OTYiLCJpYXQiOjE2Nzk1MzQzMTJ9.-7yT3flXTnf75MDs3K-cmKeC-fao0XbPprt1cem8XO4

