POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "This is a new post four",
  "author": "AL",
  "url": "http://a.b.com",
  "likes": 2020,
  "userId": "641b4e68e915305604fa739b"
}

###
DELETE http://localhost:3003/api/blogs/5a422ba71b54a676234d17fb
Content-Type: application/json
